Us s4 content article
WildCodeSchool/sugar-rush-project-backend pull request #11
Opened 2023-07-11 13:08 UTC by pwah59

Paragraphe
entity
repository
service

2023-07-11 14:40 UTC, FlorianHe requested changes
La PR n'est pas fonctionnel. Elle ne peut pas être review pour le moment

2023-07-12 09:49 UTC, alexboutemy requested changes

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/entity/Article.java
> +    private List<Paragraphe> listParags;
Be careful with your variables names.It should be explicit and in english : Paragraph instead of Paragraphe; listParagraphs instead of listParags

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/entity/Article.java
> +    }
Don't forget to change this part with your new variable name

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/entity/Paragraphe.java
> +
same here. Class Paragraph

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/repository/ParagrapheRepository.java
> +}
again:Paragraph

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/service/ArticleService.java
> +
ParagraphRepository instead of ParagrapheRepository

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/service/ArticleService.java
>      }
same here

2023-07-12 09:49 UTC, alexboutemy commented on src/main/java/com/templateproject/api/service/ArticleService.java
> +
again delete last e of paragraphe

2023-07-12 12:25 UTC, alexboutemy approved these changes

2023-07-12 12:51 UTC, Benja-san approved these changes

2023-07-12 12:51 UTC, Benja-san commented on src/main/java/com/templateproject/api/entity/Article.java
> +    //gestion des commentaires
remove dead code

2023-07-12 13:14 UTC, Benja-san approved these changes

2023-07-12 13:30 UTC, FlorianHe approved these changes

2023-07-12 13:45 UTC, merged